---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, 
                      fig.pos = 'h', fig.align = 'center', fig.width = 6, fig.height = 3)
knitr::opts_knit$set(root.dir = "C:/RajuPC/MPP Final Thesis/WorkingDirectory")
```


```{r workingdir, results="hide"}
source("source.R")
```

\setcounter{page}{37}

#Appendix:

```{r, results='asis', warning=FALSE, message=FALSE}
president <- rio::import("presidents_incumbents.csv") %>%
  select(-`Republican Incumbency`)
  
stargazer::stargazer(president, summary = FALSE, type = "latex", header = FALSE, title = "Incumbents and Winners in the U.S. election (1992-2016)")
```

```{r results='asis', warning=FALSE, message=FALSE}
summary_df1 <- merged_df5 %>%
  select(rep.share, repshare.lag, rep_incumb, unemp_gro, rural_percent, white.percent, Pop)

stargazer::stargazer(summary_df1, summary = TRUE, type = 'latex',digits = 2, header = FALSE, title = "Step I Variables: Summary Statistics", font.size = 'normalsize')

summary_df2 <- p2_merged_df8 %>%
  select(resid, rep.share, repshare.lag, pred_repshare, is.rep.2012, is.rep.2016, pop, unemp_gro, manu_share_gro, lfpr_male_gro, av_wage_gro, gini_gro, uneduc)

stargazer::stargazer(summary_df2, summary = TRUE, type = 'latex',digits = 2, header = FALSE, title = "Step III Variables: Summary Statistics", font.size = 'normalsize')

```

\pagebreak
 
```{r, results='asis', warning=FALSE, message=FALSE}
stargazer::stargazer(table100, type = "latex", summary = FALSE, header = FALSE, title = "Number of counties that turned Republican from Democrat between 2012 and 2016 and were underpredicted")
```

\pagebreak

```{r, results='asis', warning=FALSE, message=FALSE}
stargazer::stargazer(table200, summary = FALSE, type = "latex", header = FALSE, title = "Number of counties that stayed Republican between 2012 and 2016 and were underpredicted")   
```

\pagebreak

##Alternate analysis for Step III:

###Testing Rival Theories for 2016 using the difference in 2015 economic vaiables against 2014 economic variables

```{r, results='asis', warning=FALSE, message=FALSE}
stargazer::stargazer(m100, m101, m102, type = 'latex', digits = 2, header = FALSE,   
                     title = 'Testing Rival Theories for 2016 Residuals using OLS Estimate', font.size = 'normalsize',
                     dep.var.caption = "", column.labels = c("All counties", "Swing-state counties", "Rust-belt counties"), model.names = F)
```

\pagebreak

```{r, results='asis', warning=FALSE, message=FALSE}
stargazer::stargazer(swingtable, summary = FALSE, type = "latex", header = FALSE, title = "Swing States and their Counties")  
```
Source: https://en.wikipedia.org/wiki/Swing_state

```{r, results='asis', warning=FALSE, message=FALSE}
stargazer::stargazer(rusttable, summary = FALSE, type = "latex", header = FALSE, title = "Rust-belt States and their Counties")  
```
Source: https://en.wikipedia.org/wiki/Rust_Belt

##Hausman Test for Step I:

```{r, results ='asis', warning=FALSE, message=FALSE, fig.cap="Hausman Test Result"}
phtest(f2, f2random)
```

##Time-Fixed Effects Test for Step I:

```{r, results ='asis', warning = FALSE, message = FALSE, fig.cap="Testing Time-fixed effects"}
plmtest(f2, c("time"), type=("bp"))
```
