---
title: "Rough codes"
author: "Raju Adhikari"
date: "March 17, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, echo=FALSE}
library(bea.R)
library(acs)
library(magrittr)
library(httr)
library(tidyr)
library(blsAPI)
library(rjson)

setwd("C:/RajuPC/MPP Final Thesis/MPP_Thesis_Adhikari")

blskey <- "a9e62413e38741b5aeb814efc5a3d066"
beaKey <- 'C3812F4D-F498-40F8-9F36-9FF5AF65DBD7'
censusKey <- "c7ed765d1b03f4217ccc4b37d31b0dc3580db44e"
datagovkey <- "ubFrNGonfwMQm3lK04C6djaMcqFuIe5mvev4RooI"

```

```{r election}
#******Don't run this one*************#
voteshare <- read.csv("president-wide.csv") #load the csv data
voteshare <- voteshare[ -c(1, 7:9, 11) ] #remove the columns that had votes for other candidates
names(voteshare) #lists the names of all the variables(columns)
str(voteshare) #see the structure of the object

voteshare$repshare <- voteshare$trump / voteshare$totalvotes #create a new column that contains Trumps vote share
                                                              # This is our dependent variable
voteshare$demshare <- voteshare$clinton / voteshare$totalvotes #clinton's vote share
voteshare$diff_voteshare <- voteshare$demshare - voteshare$repshare # Difference in voteshare

```


```{r education, echo=FALSE, include=FALSE}
education <- read.csv("Education_county_1970-2015.csv") #load the csv data
education <- education[-c(1:3), ] #remove the rows with unncessary data

names(education) <- as.matrix(education[1, ]) #Apply the names of the first row as the title row
education <- education[-1, ] #Remove the first row

education[] <- lapply(education, function(x) type.convert(as.character(x))) ##Not sure what this one does? Assigns NA to blank space

names(education) #lists the names of all the variables(columns)
str(education) #see the structure of the object

```


```{r unemployment_mhi, echo=FALSE, include=FALSE}
unemployment_mhi <- read.csv("Unemployment_MHI_2007-2015.csv") #load the csv data
unemployment_mhi <- unemployment_mhi[-c(1:6), ] #remove the rows with unncessary data

names(unemployment_mhi) <- as.matrix(unemployment_mhi[1, ]) #Apply the names of the first row as the title row
unemployment_mhi <- unemployment_mhi[-1, ] #Remove the first row

unemployment_mhi[] <- lapply(unemployment_mhi, function(x) type.convert(as.character(x))) ##Not sure what this one does? Assigns NA to blank spaces

names(unemployment_mhi) #lists the names of all the variables(columns)
str(unemployment_mhi) #see the structure of the object

```

```{r beadata}
##***********Do not include******************#######
#BEA Regional Income Data: Blue Collar Jobs (Employment by Industry)
beaJobs <- list(
    'UserID' = beaKey ,
    'Method' = 'GetData',
    'datasetname' = 'RegionalIncome',
    'TableName' = 'CA25N' ,
    'LineCode' = '10',
    'Year' = 'ALL' ,
    'GeoFips' = 'COUNTY' ,
    'ResultFormat' = 'json'
);
beaJobs <- beaGet(beaJobs)

beaMining <- list(
    'UserID' = beaKey ,
    'Method' = 'GetData',
    'datasetname' = 'RegionalIncome',
    'TableName' = 'CA25N' ,
    'LineCode' = '200',
    'Year' = 'ALL' ,
    'GeoFips' = 'COUNTY' ,
    'ResultFormat' = 'json'
);
beaMining <- beaGet(beaMining)

beaUtilities <- list(
    'UserID' = beaKey ,
    'Method' = 'GetData',
    'datasetname' = 'RegionalIncome',
    'TableName' = 'CA25N' ,
    'LineCode' = '300',
    'Year' = 'ALL' ,
    'GeoFips' = 'COUNTY' ,
    'ResultFormat' = 'json'
);
beaUtilities <- beaGet(beaUtilities)

beaConstruction <- list(
    'UserID' = beaKey ,
    'Method' = 'GetData',
    'datasetname' = 'RegionalIncome',
    'TableName' = 'CA25N' ,
    'LineCode' = '400',
    'Year' = 'ALL' ,
    'GeoFips' = 'COUNTY' ,
    'ResultFormat' = 'json'
);
beaConstruction <- beaGet(beaConstruction)

beaManufacturing <- list(
    'UserID' = beaKey ,
    'Method' = 'GetData',
    'datasetname' = 'RegionalIncome',
    'TableName' = 'CA25N' ,
    'LineCode' = '500',
    'Year' = 'ALL' ,
    'GeoFips' = 'COUNTY' ,
    'ResultFormat' = 'json'
);
beaManufacturing <- beaGet(beaManufacturing)

beaTransportWarehouse <- list(
    'UserID' = beaKey ,
    'Method' = 'GetData',
    'datasetname' = 'RegionalIncome',
    'TableName' = 'CA25N' ,
    'LineCode' = '800',
    'Year' = 'ALL' ,
    'GeoFips' = 'COUNTY' ,
    'ResultFormat' = 'json'
);
beaTransportWarehouse <- beaGet(beaTransportWarehouse)

beaAccom_Food <- list(
    'UserID' = beaKey ,
    'Method' = 'GetData',
    'datasetname' = 'RegionalIncome',
    'TableName' = 'CA25N' ,
    'LineCode' = '1800',
    'Year' = 'ALL' ,
    'GeoFips' = 'COUNTY' ,
    'ResultFormat' = 'json'
);
beaAccom_Food <- beaGet(beaAccom_Food)
```

```{r censusqwi}
employ <- GET("api.census.gov/data/timeseries/qwi/sa?get=Emp&for=county:*&in=state:02&year=2012&quarter=1&sex=1&sex=2&agegrp=A02&agegrp=A07&ownercode=A00&seasonadj=U&industry=11&key=c7ed765d1b03f4217ccc4b37d31b0dc3580db44e") 
```


```{r census, echo=FALSE, include=FALSE}
#Census Data
geo <- geo.make(state = '*', county = '*', combine = F, combine.term = "aggregate", check = FALSE, key = "auto")
male <- acs.fetch(endyear =2015, span =5, geo, dataset = 'acs', variable = 'B01001_002', col.names = 'auto')

estimate(male)
estimate(male) -> male.estimate

cbind(male.estimate, standard.error(male)) -> male1
rownames(male1)

rownames(male1) %>% cbind(male1) -> male1
```

```{r}
#Voteshare Data (1992-2016)
voteshare_new <- read.table(file = 'full-us-presidential-counties-1960-2016.tsv', sep = '\t', header = TRUE)

voteshare_recent <- voteshare_new[voteshare_new$year >= "1992",] #Choosing years after 1992
voteshare_recent <- voteshare_recent[voteshare_recent$year < "2016",] #Removing year 2016

#Separating the democrats data and republicans data into separate dataframes
voteshare_recent_rep <- voteshare_recent [voteshare_recent$party == "R", ]
names(voteshare_recent_rep)[names(voteshare_recent_rep)=="vote.percent"] <- "rep.percent"
names(voteshare_recent_rep)[names(voteshare_recent_rep)=="vote.count"] <- "rep.count"
names(voteshare_recent_rep)[names(voteshare_recent_rep)=="is.national.winner"] <- "is.rep.nat.winner"
names(voteshare_recent_rep)[names(voteshare_recent_rep)=="national.party.count"] <- "nat.rep.count"
names(voteshare_recent_rep)[names(voteshare_recent_rep)=="national.party.percent"] <- "nat.rep.percent"

voteshare_recent_rep$party <- NULL

voteshare_recent_dem <- voteshare_recent [voteshare_recent$party == "D", ]
names(voteshare_recent_dem)[names(voteshare_recent_dem)=="vote.percent"] <- "dem.percent"
names(voteshare_recent_dem)[names(voteshare_recent_dem)=="vote.count"] <- "dem.count"
names(voteshare_recent_dem)[names(voteshare_recent_dem)=="is.national.winner"] <- "is.dem.nat.winner"
names(voteshare_recent_dem)[names(voteshare_recent_dem)=="national.party.count"] <- "nat.dem.count"
names(voteshare_recent_dem)[names(voteshare_recent_dem)=="national.party.percent"] <- "nat.dem.percent"

voteshare_recent_dem$party <- NULL

#Merging the two dataframes
election_df <- merge(voteshare_recent_rep, voteshare_recent_dem, all = T)
```

